# Generated by Django 4.1.4 on 2022-12-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('producteur', models.CharField(max_length=128)),
                ('acteur', models.CharField(max_length=128)),
                ('heure', models.TimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cinemas')),
                ('note', models.FloatField(default=0.0)),
                ('synopsis', models.TextField(blank=True)),
            ],
        ),
    ]
